openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /orders/phone/:
    get:
      operationId: listPhones
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    user:
                      type: integer
                    number:
                      type: string
                      maxLength: 20
                  required:
                  - number
          description: ''
    post:
      operationId: createPhone
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                user:
                  type: integer
                number:
                  type: string
                  maxLength: 20
              required:
              - number
          application/x-www-form-urlencoded:
            schema: *id001
          multipart/form-data:
            schema: *id001
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  user:
                    type: integer
                  number:
                    type: string
                    maxLength: 20
                required:
                - number
          description: ''
  /orders/phone/{id}/:
    get:
      operationId: retrievePhone
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  user:
                    type: integer
                  number:
                    type: string
                    maxLength: 20
                required:
                - number
          description: ''
    put:
      operationId: updatePhone
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id002
              properties:
                user:
                  type: integer
                number:
                  type: string
                  maxLength: 20
              required:
              - number
          application/x-www-form-urlencoded:
            schema: *id002
          multipart/form-data:
            schema: *id002
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  user:
                    type: integer
                  number:
                    type: string
                    maxLength: 20
                required:
                - number
          description: ''
    patch:
      operationId: partial_updatePhone
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id003
              properties:
                user:
                  type: integer
                number:
                  type: string
                  maxLength: 20
          application/x-www-form-urlencoded:
            schema: *id003
          multipart/form-data:
            schema: *id003
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  user:
                    type: integer
                  number:
                    type: string
                    maxLength: 20
                required:
                - number
          description: ''
    delete:
      operationId: destroyPhone
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0442\u0435\u043B\u0435\u0444\u043E\u043D\
        \u043E\u043C \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /categories/:
    get:
      operationId: listCategorys
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u0440\
        \u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430\
        \ \u0432\u0441\u0435\u0445 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\
        \u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    name:
                      type: string
                      maxLength: 50
                    shops:
                      type: array
                      items:
                        type: integer
                  required:
                  - name
          description: ''
  /shops/:
    get:
      operationId: listShops
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u0440\
        \u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430\
        \ \u043C\u0430\u0433\u0430\u0437\u0438\u043D\u043E\u0432, \u043F\u0440\u0438\
        \u043D\u0438\u043C\u0430\u044E\u0449\u0438\u0445 \u0437\u0430\u043A\u0430\u0437\
        \u044B"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    name:
                      type: string
                      maxLength: 50
                    url:
                      type: string
                      format: uri
                      nullable: true
                      maxLength: 200
                      pattern: "^(?:[a-z0-9\\.\\-\\+]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:25[0-5]|2[0-4]\\\
                        d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}|\\\
                        [[0-9a-f:\\.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
                        -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\\
                        .(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
                        .?|localhost))(?::\\d{2,5})?(?:[/?#][^\\s]*)?\\Z"
                    state:
                      type: boolean
                  required:
                  - name
          description: ''
  /products/:
    get:
      operationId: listProducts
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u0440\
        \u043E\u0441\u043C\u043E\u0442\u0440\u0430 \u0442\u043E\u0432\u0430\u0440\u043E\
        \u0432 (\u0432\u0441\u0435\u0445, \u043F\u043E \u043A\u0430\u0442\u0435\u0433\
        \u043E\u0440\u0438\u0438, \u043F\u043E \u043C\u0430\u0433\u0430\u0437\u0438\
        \u043D\u0443 \u0438\u043B\u0438 \u043E\u0434\u043D\u043E\u0433\u043E \u043F\
        \u043E id \u0442\u043E\u0432\u0430\u0440\u0430)"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /orders/:
    get:
      operationId: listOrders
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0437\u0430\u043A\u0430\u0437\u0430\u043C\
        \u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    put:
      operationId: UpdateOrders
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0437\u0430\u043A\u0430\u0437\u0430\u043C\
        \u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /cart/:
    get:
      operationId: listCarts
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u043A\u043E\u0440\u0437\u0438\u043D\u043E\
        \u0439 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateCart
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u043A\u043E\u0440\u0437\u0438\u043D\u043E\
        \u0439 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateCart
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u043A\u043E\u0440\u0437\u0438\u043D\u043E\
        \u0439 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyCart
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u043A\u043E\u0440\u0437\u0438\u043D\u043E\
        \u0439 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '204':
          description: ''
  /address/:
    get:
      operationId: listContacts
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0430\u0434\u0440\u0435\u0441\u0441\u0430\
        \u043C\u0438 \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateContact
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0430\u0434\u0440\u0435\u0441\u0441\u0430\
        \u043C\u0438 \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    patch:
      operationId: PartialUpdateContact
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0430\u0434\u0440\u0435\u0441\u0441\u0430\
        \u043C\u0438 \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyContact
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0440\u0430\
        \u0431\u043E\u0442\u044B \u0441 \u0430\u0434\u0440\u0435\u0441\u0441\u0430\
        \u043C\u0438 \u043F\u043E\u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439"
      parameters: []
      responses:
        '204':
          description: ''
  /partners/state/:
    get:
      operationId: listPartnerStates
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F \u0441\u0442\u0430\u0442\u0443\u0441\
        \u0430 \u043F\u0430\u0440\u0442\u043D\u0435\u0440\u0430"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreatePartnerState
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F \u0441\u0442\u0430\u0442\u0443\u0441\
        \u0430 \u043F\u0430\u0440\u0442\u043D\u0435\u0440\u0430"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /partners/orders/:
    get:
      operationId: listPartnerOrders
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u043F\u043E\
        \u043B\u0443\u0447\u0435\u043D\u0438\u044F \u0437\u0430\u043A\u0430\u0437\u043E\
        \u0432 \u043F\u043E\u0441\u0442\u0430\u0432\u0449\u0438\u043A\u0430\u043C\u0438"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /users/create/:
    post:
      operationId: CreateUser
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0441\u043E\
        \u0437\u0434\u0430\u043D\u0438\u044F \u043D\u043E\u0432\u043E\u0433\u043E\
        \ \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id004
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                password:
                  type: string
                  writeOnly: true
                  maxLength: 128
                  minLength: 5
                name:
                  type: string
                  maxLength: 255
              required:
              - email
              - password
              - name
          application/x-www-form-urlencoded:
            schema: *id004
          multipart/form-data:
            schema: *id004
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                    format: email
                    maxLength: 255
                  name:
                    type: string
                    maxLength: 255
                required:
                - email
                - name
          description: ''
  /users/token/:
    post:
      operationId: CreateCreateToken
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0441\u043E\
        \u0437\u0434\u0430\u043D\u0438\u044F \u043D\u043E\u0432\u043E\u0433\u043E\
        \ \u0442\u043E\u043A\u0435\u043D\u0430 \u043F\u0440\u0438 \u0430\u0432\u0442\
        \u043E\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u043F\u043E\u043B\u044C\u0437\
        \u043E\u0432\u0430\u0442\u0435\u043B\u044F"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /partners/update/:
    post:
      operationId: CreatePartnerUpdate
      description: "\u041A\u043B\u0430\u0441\u0441 \u0434\u043B\u044F \u0438\u043C\
        \u043F\u043E\u0440\u0442\u0430 \u043F\u0440\u0430\u0439\u0441\u0430 \u043E\
        \u0442 \u043F\u043E\u0441\u0442\u0430\u0432\u0449\u0438\u043A\u0430"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
